name: Deploy and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        cd backend
        npm install
        cd ../frontend
        npm install
        cd ..

    - name: Run Tests
      run: |
        cd backend
        npm run test:cov
        cd ../frontend
        npm run test:cov
        cd ..

    - name: Upload Test Report to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-1'  # 根据您的 S3 区域设置
        SOURCE_DIR: 'reports/backend/coverage'  # 测试报告目录
        # DEST_DIR: 's3://test-reports'  # S3 中的目标目录

  package:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20 # 使用 Node.js 20

    - name: Install Dependencies
      run: npm install

    - name: Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build --prod
      # outputs:
      #   frontend-dist: ${{ steps.build-frontend.outputs.frontend-dist }}

    - name: Build Backend
      working-directory: backend
      run: |
        npm install
        npm run build
      # outputs:
      #   backend-dist: ${{ steps.build-backend.outputs.backend-dist }}

  deploy:
    runs-on: ubuntu-latest
    needs: package
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_KEY }}
        script: |
          cd /var/www/bidding-platform
          git pull origin master || git clone https://github.com/dreaife/bidding-platform.git .
          
          # 构建前端
          cd frontend
          npm install
          npm run build --prod
          
          # 构建后端
          cd ../backend
          npm install
          npm run build
          
          # 创建 public 目录并移动前端文件
          mkdir -p public
          cp -r ../frontend/dist/frontend/browser/* public/
          
          # 启动后端服务
          pm2 restart all || pm2 start dist/main.js --name bidding-platform-backend
